# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ae656f042550517d5704139bda4b411d5a7132f5be516257af7ead4da54a2b63668fbe8efb06742469a38c7dbbc83b9743cbe5bd7271f034dfe2b2ece3c2556

test:
  secret_key_base: 196d71283c11e63d8fa5ee3b4b5e52d89eb6dfb33cbf1744e1c7eba04e3f3d485a00d3ddac2509f9ec65e589be012705fb3b4575bfbf49d16a9d9bdf53cedf01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
